language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: N4AvtIOwZNgGYevVkFGzCQfSg4lpdKnWpnKEY6ko/ytVvFO+hxdlAkjqxE4kcy7MWBXx0yGkkc0gnvRqPeoUa17SuEUUt5MzpZB+GVVxWExI3oooh3XIqIfoUC2/xedYdsHrjgVRwrjsU/8okUbqjlWOrvxxN7ZGtPKhDYCPtj0=
  - secure: lZNocIdZMAzogXlFD/Tfl6DeRPfN9sYdiuE0avQRrigd+lVguT28ooDpTI5dWIjzNL9uENUrPSJs8BM42+emZGZtfsmZePEZXNh1Onk4vkJcAobl9ZUYvv8ZuA0kcEqRffxiyrt0cRsJVmnpaVodFrKbf7ZyO1blwJ6eFpdaWTE=
